### ISSUE TITLE
rake db:create not working

### ISSUE THREAD

**Issue by Miroshni4enko** [mirego/microscope#38]
gems/microscope-1.0.1/lib/microscope.rb : acts_as_microscope
` return unless table_exists?` condition effect  `rake db:create `
Could you please fix it?

**Comment by remiprev** [comment]
Hi Vyacheslav,

Could you please provide a step-by-step plan on how to reproduce the issue? That way we’ll know what the exact problem and will be much confident that we’ll be fixin the right thing 😄

Thank you!

**Comment by Miroshni4enko** [comment]
Hi Rémi!)
Thank you for so quick response.
**Steps:**
1. Add microscope gem to rails project
2. Run `bundle install`
3. Add acts_as_microscope only: [:approved] for model class with aprroved boolean field
4. Run `rake db:drop`
5. Run `rake db:create`
ER: db is created 
AR: error - rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "development_db" does not exist

**Comment by Miroshni4enko** [comment]
Hi Rémi!)
Any updates?

**Comment by remiprev** [comment]
Hi Vyacheslav,

My Ruby setup is not quite as ready as I thought. I’m working on how to reproduce the bug in a test case.

I’ll keep you posted here!

**Comment by Miroshni4enko** [comment]
Hi Rémi!)
Thank you!

**Comment by remiprev** [comment]
@Miroshni4enko #39 should fix the issue! 🎉 I’ll release `microscope-1.1.0` after merging it.
