### ISSUE TITLE
Gem blocking rake assets:precompile

### ISSUE THREAD

**Issue by jdwyah** [mirego/microscope#41]
I'm having a very similar issue to https://github.com/mirego/microscope/issues/38  but it occurs when I run 
`RAILS_ENV=production rake assets:precompile` in my dockerfile. 

I belive the fix in #38 doesn't work because it throws a ActiveRecord::ConnectionNotEstablished error, not a ActiveRecord::NoDatabaseError. 

Making that rescue a bit more expansive would be delightful. Thanks.

**Comment by remi** [comment]
Hi Jeff,

Good catch. I’ll look into that!

**Comment by remi** [comment]
> Making that rescue a bit more expansive would be delightful. Thanks.

Looks like [`ActiveRecord::ActiveRecordError`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/errors.rb#L7-L8) is what we’re looking for.

I’m on it.

**Comment by remi** [comment]
@jdwyah [`microscope-1.1.1`](https://rubygems.org/gems/microscope/versions/1.1.1) has been released! 🎉

**Comment by jdwyah** [comment]
Just want to let you know that this does indeed fix it for me. Thanks!
